[tool.interrogate]
ignore-init-module = true
ignore-module = true
exclude = [
    "manage.py",
    "products/migrations", "products/admin.py", "products/apps.py",
]
ignore-regex = ["Meta", "__str__", "setUpTestData", "setUp", "get_absolute_url"]